#ifndef __SPECTCMD_H__
#define __SPECTCMD_H__

#include <inttypes.h>

#define SPECTCMD_CMD_GETRESOURCE (0x00)
#define SPECTCMD_CMD_SETWIFI (0x01)
#define SPECTCMD_CMD_STARTSCAN (0x02)
#define SPECTCMD_CMD_SAVESNA (0x03)
#define SPECTCMD_CMD_LOADSNA (0x06)
#define SPECTCMD_CMD_SETFILEFILTER (0x07)
#define SPECTCMD_CMD_PLAYTAPE   (0x08)
#define SPECTCMD_CMD_RECORDTAPE (0x09)
#define SPECTCMD_CMD_STOPTAPE   (0x0A)
#define SPECTCMD_CMD_ENTERDIR   (0x0B)
#define SPECTCMD_CMD_SETVIDEOMODE (0x0C)
#define SPECTCMD_CMD_RESET (0x0D)
#define SPECTCMD_CMD_KBDDATA (0x0E)
#define SPECTCMD_CMD_NMIREADY (0x0F)
#define SPECTCMD_CMD_LEAVENMI (0x10)
#define SPECTCMD_CMD_DETECTSPECTRUM (0x11)
#define SPECTCMD_CMD_FASTLOAD (0x12)
#define SPECTCMD_CMD_FASTLOAD_DATA (0x13)
#define SPECTCMD_CMD_PLAYTAPE_FAST (0x14)
#define SPECTCMD_CMD_ROMCRC (0x15)
#define SPECTCMD_CMD_LOADTRAP (0x16)
#define SPECTCMD_CMD_SAVETRAP (0x17)
#define SPECTCMD_CMD_SAVEDATA (0x18)
#define SPECTCMD_CMD_MEMDATA (0x19)
#define SPECTCMD_CMD_KEYINJECT (0x1A)
#define SPECTCMD_CMD_128RESET (0x1B)
// Esxdos-like calls
#define SPECTCMD_CMD_ESXDOS_DISKINFO (0x40)

// POSIX File
#define SPECTCMD_CMD_GETCWD   (0x20)
#define SPECTCMD_CMD_CHDIR    (0x21)
#define SPECTCMD_CMD_OPEN     (0x22)
#define SPECTCMD_CMD_CLOSE    (0x23)
#define SPECTCMD_CMD_READ     (0x24)
#define SPECTCMD_CMD_WRITE    (0x25)
#define SPECTCMD_CMD_OPENDIR  (0x26)
#define SPECTCMD_CMD_READDIR  (0x27)
#define SPECTCMD_CMD_CLOSEDIR (0x28)

// Networking
#define SPECTCMD_CMD_SOCKET         (0x29)
#define SPECTCMD_CMD_CONNECT        (0x2A)
#define SPECTCMD_CMD_SENDTO         (0x2B)
#define SPECTCMD_CMD_RECVFROM       (0x2C)
#define SPECTCMD_CMD_GETHOSTBYNAME  (0x2D)
#define SPECTCMD_CMD_GETHOSTBYADDR  (0x2E)

#define SPECTCMD_CMD_WGET           (0x2F)



void spectcmd__request(void);
void spectcmd__init(void);


void spectrum_model_detected(uint8_t model, uint8_t flags);

#endif
