COMMONSIMFILES=                             \
tests/t014.vhd                              \
tests/t012.vhd                              \
tests/t009.vhd                              \
tests/t011.vhd                              \
tests/t008.vhd                              \
tests/t006.vhd                              \
tests/t005.vhd                              \
tests/t004.vhd                              \
tests/t001.vhd                              \
tests/t002.vhd                              \
tests/t013.vhd                              \
tests/t010.vhd                              \
tests/t007.vhd                              \
tests/t003.vhd                              \
bfm/bfm_usbdevice_p.vhd                     \
bfm/bfm_qspiram.vhd                         \
bfm/bfm_audiocap.vhd                        \
bfm/bfm_ula.vhd                             \
bfm/bfm_spectrum.vhd                        \
bfm/bfm_spectrum_p.vhd                      \
bfm/bfm_spimaster.vhd                       \
bfm/bfm_reset.vhd                           \
bfm/bfm_reset_p.vhd                         \
bfm/bfm_clock.vhd                           \
bfm/bfm_clock_p.vhd                         \
bfm/bfm_spimaster_p.vhd                     \
bfm/bfm_ctrlpins_p.vhd                      \
bfm/bfm_ctrlpins.vhd                        \
bfm/bfm_audiocap_p.vhd                      \
bfm/bfm_qspiram_p.vhd                       \
bfm/bfm_usbdevice.vhd                       \
bfm/bfm_ula_p.vhd                           \
fpga-spectrum/T80/T80a.vhd                  \
fpga-spectrum/T80/T80_Reg.vhd               \
fpga-spectrum/T80/T80_MCode.vhd             \
fpga-spectrum/T80/T80se.vhd                 \
fpga-spectrum/T80/T80_Pack.vhd              \
fpga-spectrum/T80/T80_ALU.vhd               \
fpga-spectrum/T80/T80.vhd                   \
firmware/spectrum_rom_chip.vhd              \
test_c.vhd                                  \
tbc_device_p.vhd                            \
z80_top.vhd                                 \
tb_spi_slave_fifo.vhd                       \
tb_interfacez_top.vhd                       \
logger.vhd                                  \
tb_psram.vhd                                \
ay8910.vhd                                  \
clockmux_sim.vhd                            \
sim.vhd                                     \
oddrff.vhd                                  \
z80_sim.vhd                                 \
m25p16/M25P16.vhd                           \
SN74LCX245FT.vhd                            \
corepll_sim.vhd                             \
txt_util.vhd                                \
m25p16/M25P16_driver.vhd                    \
m25p16/mem_util_pkg.vhd                     \
m25p16/Internal_Logic.vhd                   \
m25p16/ACDC_check.vhd                       \
m25p16/Memory_Access.vhd                    \
spectrum_ram.vhd                            \
tbc_device_e.vhd                            \
tb_top.vhd                                  \
videoram_sim.vhd                            \
tb_tap_player.vhd                           \
usbxcvr_sim.vhd                             \

LOCALSIMFILES=

DESIGNFILES=                                           \
usb/usb1_crc16.vhd                                  \
usb/usbpkg.vhd                                      \
usb/usb_trans.vhd                                   \
epram.vhd                                           \
async_pulse2.vhd                                    \
async_pulse_data.vhd                                \
usb/maj_filter.vhd                                  \
usb/usb_dpll.vhd                                    \
ym2149/ym2149_clocking.vhd                          \
ym2149/ym2149_noisegen.vhd                          \
ym2149/ym2149_envelopegen.vhd                       \
ym2149/ym2149_volume.vhd                            \
smallfifo.vhd                                       \
spi_slave_fifo.vhd                                  \
swfifo.vhd                                          \
smallfifo_dualclock.vhd                             \
command_fifo_single.vhd                             \
qspi_slave_resync.vhd                               \
scope.vhd                                           \
ym2149/ym2149_mixer.vhd                             \
ym2149/ym2149_tonegen.vhd                           \
ym2149/ym2149_regs.vhd                              \
audiomult.vhd                                       \
ym2149/ym2149.vhd                                   \
dac_dsm3.vhd                                        \
zxaudio.vhd                                         \
tappkg.vhd                                          \
usb/usb_txclkgen.vhd                                \
usb/usb_filter.vhd                                  \
async_dualpulse_data.vhd                            \
usb/usb_epmem.vhd                                   \
usb/usb1_pd.vhd                                     \
usb/usb1_crc5.vhd                                   \
ahb_arb.vhd                                         \
usb/usb_tx_phy.vhd                                  \
iobuf.vhd                                           \
ahbpkg.vhd                                          \
psram.vhd                                           \
tap_fifo.vhd                                        \
tap_pulse.vhd                                       \
resource_fifo.vhd                                   \
delay_filter.vhd                                    \
businterface.vhd                                    \
generic_dp_ram2.vhd                                 \
videogen.vhd                                        \
border_capture.vhd                                  \
insn_detector.vhd                                   \
async_pulse.vhd                                     \
gh_vhdl_lib/memory/gh_fifo_async_sr_wf.vhd          \
qspi_slave.vhd                                      \
gh_vhdl_lib/custom_MSI/gh_gray2binary.vhd           \
gh_vhdl_lib/custom_MSI/gh_binary2gray.vhd           \
gh_vhdl_lib/memory/gh_sram_1wp_2rp_sc.vhd           \
gh_vhdl_lib/memory/gh_fifo_async_rrd_sr_wf.vhd      \
fifo2.vhd                                           \
sdram_hamster.vhd                                   \
sync.vhd                                            \
generic_dp_ram.vhd                                  \
rstgen.vhd                                          \
zxinterface.vhd                                     \
syncv.vhd                                           \
busopdet.vhd                                        \
sdram_ctrl.vhd                                      \
wishbonepkg.vhd                                     \
screencap.vhd                                       \
spi_interface.vhd                                   \
logiccapture.vhd                                    \
interfacez_io.vhd                                   \
command_fifo.vhd                                    \
videogen_fifo.vhd                                   \
glitch_filter.vhd                                   \
tap_player.vhd                                      \
tap_engine.vhd                                      \
ram_adaptor.vhd                                     \
obuf.vhd                                            \
usb/usbhostctrl.vhd                                 \
usb/usb_phy.vhd                                     \
usb/usb_rx_phy.vhd                                  \
ahbreq.vhd                                          \
ahbreq_sync.vhd


LOCALDESIGNFILES= \
	zxinterfacepkg.vhd \
	interfacez_top.vhd

ALTERAFILES= \
altera_mf.vhd \
altera_mf_components.vhd


ALTERAFILESF=$(addprefix ../../simulation/altera/, $(ALTERAFILES))


SIMFILES=$(addprefix ../../simulation/, $(COMMONSIMFILES))
DESIGNFILESF=$(addprefix ../../rtl/common/, $(DESIGNFILES))
LOCALDESIGNFILESF=$(addprefix ../rtl/, $(LOCALDESIGNFILES))



all: work-obj93.cf altera_mf-obj93.cf

work-obj93.cf:
	ghdl -i $(SIMFILES) $(LOCALSIMFILES) $(DESIGNFILESF) $(LOCALDESIGNFILESF)
	
altera_mf-obj93.cf:
	ghdl -i --work=altera_mf $(ALTERAFILESF)
