CMD_GET_RESOURCE equ $00
CMD_SETUP_WIFI  equ $01
CMD_START_SCAN equ $02

CMD_SAVE_SNA	equ $05	
CMD_LOAD_SNA	equ $06
CMD_SET_FILE_FILTER	equ $07
CMD_PLAY_TAPE	equ $08
CMD_RECORD_TAPE	equ $09
CMD_STOP_TAPE	equ $0A
CMD_CHDIR	equ $0B

