CMD_GET_RESOURCE equ $00
CMD_SETUP_WIFI  equ $01
CMD_START_SCAN equ $02

CMD_SAVE_SNA	equ $03	
CMD_LOAD_SNA	equ $06
CMD_SET_FILE_FILTER	equ $07
  FILE_FILTER_ALL	equ $00
  FILE_FILTER_SNAPSHOTS	equ $01
  FILE_FILTER_TAPES	equ $02

CMD_PLAY_TAPE	equ $08
CMD_RECORD_TAPE	equ $09
CMD_STOP_TAPE	equ $0A
;CMD_CHDIR	equ $0B
CMD_SETVIDEOMODE       equ $0C
CMD_RESET       equ $0D
CMD_KBDINPUT	equ $0E
CMD_NMIREADY	equ $0F
CMD_LEAVENMI	equ $10
CMD_SPECTRUMDETECT	equ $11
CMD_FASTLOAD	equ $12
CMD_FASTLOAD_DATA	equ $13
CMD_ROMCRC	equ $15
CMD_LOADTRAP	equ $16
CMD_SAVETRAP	equ $17
CMD_SAVEDATA	equ $18
CMD_MEMDATA     equ $19
CMD_KEYINJECT   equ $1A
CMD_128RESET    equ $1B


CMD_GETCWD	   EQU $20
CMD_CHDIR 	   EQU $21
CMD_OPEN  	   EQU $22
CMD_CLOSE 	   EQU $23
CMD_READ           EQU $24
CMD_WRITE          EQU $25
CMD_OPENDIR        EQU $26
CMD_READDIR        EQU $27
CMD_CLOSEDIR       EQU $28

CMD_SOCKET         EQU $29
CMD_CONNECT        EQU $2A
CMD_SENDTO         EQU $2B
CMD_RECVFROM       EQU $2C
CMD_GETHOSTBYNAME  EQU $2D
;CMD_GETHOSTBYADDR  EQU $2E
CMD_WGET           EQU $2F
CMD_STRERROR       EQU $30
; Boot commands
BOOT_CMD_CHECKCRC	equ $00
BOOT_CMD_LOADTAP	equ $01
