NMIMENU__HANDLEKEY:
	LD	HL, NMI_MENU
	
        CP	$26 	; A key
        JR	NZ, _n1
        JP	MENU__CHOOSENEXT
_n1:
        CP	$25     ; Q key
        JR	NZ, _n2
        JP	MENU__CHOOSEPREV
_n2:
        CP	$21     ; ENTER key
        JR	NZ, _n3
        JP	MENU__ACTIVATE
_n3:
	RET
        

NMIENTRY1HANDLER:

NMIENTRY2HANDLER:
	JP	SNASAVE

NMIENTRY3HANDLER:

NMIENTRY4HANDLER:
        RET
NMIENTRY5HANDLER:
        LD	A,1
        LD	(NMIEXIT), A
        RET
        
NMIMENU__SETUP:
       	LD	IX, NMI_MENU
        LD	(IX + FRAME_OFF_WIDTH), 28 ; Menu width 24
        LD	(IX + FRAME_OFF_NUMBER_OF_LINES), 5 ; Menu visible entries
        LD	(IX + MENU_OFF_DATA_ENTRIES), 5 ; Menu actual entries 
        LD 	(IX + MENU_OFF_SELECTED_ENTRY), 0 ; Selected entry
        LD	(IX+FRAME_OFF_TITLEPTR), LOW(NMIMENUTITLE)
        LD	(IX+FRAME_OFF_TITLEPTR+1), HIGH(NMIMENUTITLE)
        ; Entry 1
        LD	(IX+MENU_OFF_FIRST_ENTRY), 0 ; Flags
        LD	(IX+MENU_OFF_FIRST_ENTRY+1), LOW(NMIENTRY1)
        LD	(IX+MENU_OFF_FIRST_ENTRY+2), HIGH(NMIENTRY1);

        LD	(IX+MENU_OFF_FIRST_ENTRY+3), 0 ; Flags
        LD	(IX+MENU_OFF_FIRST_ENTRY+4), LOW(NMIENTRY2)
        LD	(IX+MENU_OFF_FIRST_ENTRY+5), HIGH(NMIENTRY2);
        
        LD	(IX+MENU_OFF_FIRST_ENTRY+6), 0 ; Flags
        LD	(IX+MENU_OFF_FIRST_ENTRY+7), LOW(NMIENTRY3)
        LD	(IX+MENU_OFF_FIRST_ENTRY+8), HIGH(NMIENTRY3)
        
        LD	(IX+MENU_OFF_FIRST_ENTRY+9), 0 ; Flags
        LD	(IX+MENU_OFF_FIRST_ENTRY+10), LOW(NMIENTRY4)
        LD	(IX+MENU_OFF_FIRST_ENTRY+11), HIGH(NMIENTRY4)

        LD	(IX+MENU_OFF_FIRST_ENTRY+12), 0 ; Flags
        LD	(IX+MENU_OFF_FIRST_ENTRY+13), LOW(NMIENTRY5)
        LD	(IX+MENU_OFF_FIRST_ENTRY+14), HIGH(NMIENTRY5)

	LD	(IX+MENU_OFF_CALLBACKPTR), LOW(NMIMENUCALLBACKTABLE)
        LD	(IX+MENU_OFF_CALLBACKPTR+1), HIGH(NMIMENUCALLBACKTABLE)

        LD 	(IX+MENU_OFF_DISPLAY_OFFSET), 0
        LD 	(IX+MENU_OFF_SELECTED_ENTRY), 0
        RET

NMIMENUCALLBACKTABLE:
	DEFW NMIENTRY1HANDLER
        DEFW NMIENTRY2HANDLER
        DEFW NMIENTRY3HANDLER
        DEFW NMIENTRY4HANDLER
        DEFW NMIENTRY5HANDLER

NMIMENUTITLE:
	DB 	"ZX Interface Z", 0
NMIENTRY1: DB	"Load snapshot", 0
NMIENTRY2: DB	"Save snapshot", 0
NMIENTRY3: DB	"Play/Stop tape", 0
NMIENTRY4: DB	"Setup...", 0
NMIENTRY5: DB	"Exit", 0
