
PORT_SCRATCH0	equ $03
PORT_SCRATCH1	equ $05
PORT_CMD_FIFO_STATUS equ $07
PORT_CMD_FIFO_DATA equ $09
PORT_RESOUCE_FIFO_STATUS equ $0b
PORT_RESOURCE_FIFO_DATA equ $0d
PORT_RAM_ADDR_0 equ $11
PORT_RAM_ADDR_1 equ $13
PORT_RAM_ADDR_2 equ $15
PORT_RAM_DATA equ $17
PORT_ULA equ $fe
