
PORT_SCRATCH0	equ $23
PORT_MISCCTRL	equ $27
PORT_CMD_FIFO_STATUS equ $2B
PORT_CMD_FIFO_DATA equ $67
PORT_RESOURCE_FIFO_STATUS equ $2F
PORT_RESOURCE_FIFO_DATA equ $33
PORT_RAM_ADDR_0 equ $37
PORT_RAM_ADDR_1 equ $3B
PORT_RAM_ADDR_2 equ $3F
PORT_RAM_DATA 	equ $63
PORT_MEMSEL   	equ $6b
PORT_NMIREASON	equ $6F



PORT_ULA equ $fe
